
name: Prod

on: 
 push:
  branches: 
   - main 
  paths:
   - 'prod/**'

jobs:
  #prod-check:
      #if: ${{ github.ref == 'refs/heads/main' }}
     build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLIENT_SECRET }}

      - run: |
          az deployment group create -f ./prod/main.bicep -g Bicep-RG001