# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on: 
 push:
  branches:
   -  main
  paths:
   - 'test/**'
  

jobs:
  #prod-check:
      #if: ${{ github.ref == 'refs/heads/main' }}
     build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLIENT_SECRET02 }}

      - run: |
          az deployment sub create \
           --name demoDeployment \
           --location westeurope \
           --template-file ./test/main.bicep \
           --parameters @main.parameters.json

# --parameters rgname=RG002 rglocation=westeurope
