# This is a basic workflow to help you get started with Actions

name: Workflow02

# Controls when the workflow will run
on: [push]
jobs:
  prod-check:
      if: ${{ github.ref == 'refs/heads/main' }}
     
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLIENT_SECRET }}

      - run: |
          az deployment group create -f ./dev/main.bicep -g Bicep-RG001
